server:
    port: 8080
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: alessandrau!
        url: jdbc:mysql://212.131.189.19:30016/alessandrau
        username: alessandrau
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
       mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER